# Generated by Django 4.0.5 on 2022-06-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.CharField(choices=[('CMassX', 'CMassX'), ('CMassY', 'CMassY'), ('CMassZ', 'CMassZ'), ('FWHMX', 'FWHMX'), ('FWHMY', 'FWHMY'), ('FWHMZ', 'FWHMZ'), ('Ghost', 'Ghost'), ('BrightGhost', 'BrightGhost')], default='green', max_length=12)),
            ],
        ),
    ]
